name: Hakyll Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache stack folder
      uses: actions/cache@v3
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}

    - name: Build Site
      run: |
        stack --no-nix --system-ghc build
        stack --no-nix --system-ghc exec site build

    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: _site
